# Financiamento do projeto (opcional). Remova o comentário e preencha o que usar.
# Docs: https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: [lhzin0]
# ko_fi: <usuario>
# buy_me_a_coffee: <usuario>
# custom: ["https://lhzin0.github.io/auroraplay/"]
